version: '3.8'

services:
  api:
    container_name: nadin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=3000
      - DATABASE_URL=mysql://root:password@mysql:3306/nadin
      - ACCESS_TOKEN_SECRET=your_jwt_secret
      - REFRESH_TOKEN_SECRET=your_refresh_secret
      - ACCESS_TOKEN_EXPIRATION=1h
      - REFRESH_TOKEN_EXPIRATION=1d
    ports:
      - "3001:3000"
    volumes:
      - ./files:/app/files
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: mysql_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nadin
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 